import { Product } from "@/types/product";

const shopData: Product[] = [
  // --- Web & Landings ---
  {
    id: 101,
    title: "Landing Page Express",
    category: "Web",
    price: 150000,
    reviews: 5,
    description: "1 página optimizada (hero, beneficios, CTA), responsive, textos IA + edición.",
    inclusions: ["1 página optimizada", "Diseño responsive", "Textos base IA + edición"],
    exclusions: ["Funciones complejas", "Formularios custom", "Integraciones"],
    imgs: {
      thumbnails: ["/images/products/product-landing.png"],
      previews: ["/images/products/product-landing.png"],
    },
  },
  {
    id: 102,
    title: "Web Corporativa Básica",
    category: "Web",
    price: 350000,
    reviews: 4,
    description: "Home, Servicios, Sobre, Contacto, Blog básico; responsive + SEO on-page.",
    inclusions: ["Home + 4 secciones", "Blog básico", "SEO on-page inicial"],
    exclusions: ["E-commerce", "CRM", "Reservas complejas"],
    imgs: {
      thumbnails: ["/images/products/web-premium.png"],
      previews: ["/images/products/web-premium.png"],
    },
  },
  {
    id: 103,
    title: "Web Corporativa Pro",
    category: "Web",
    price: 550000,
    reviews: 5,
    description: "Incluye Portfolio, FAQs, 2 formularios extra y optimización de velocidad.",
    inclusions: ["Todo lo de Básica", "Portfolio + FAQs", "Optimización velocidad"],
    exclusions: ["Funciones dinámicas avanzadas"],
    imgs: {
      thumbnails: ["/images/products/web-premium.png"],
      previews: ["/images/products/web-premium.png"],
    },
  },
  {
    id: 104,
    title: "E-commerce Ligero",
    category: "Web",
    price: 750000,
    reviews: 5,
    description: "Tienda hasta 30 productos, checkout Stripe/PayPal, categorías básicas.",
    inclusions: ["Hasta 30 productos", "Pasarela de pago", "Categorías básicas"],
    exclusions: ["Integraciones ERP", "Suscripciones complejas"],
    imgs: {
      thumbnails: ["/images/products/product-ecommerce.png"],
      previews: ["/images/products/product-ecommerce.png"],
    },
  },
  {
    id: 105,
    title: "Rediseño Web Anticuada",
    category: "Web",
    price: 400000,
    reviews: 4,
    description: "Mismo contenido, nuevo diseño responsive, mejora velocidad + mobile-first.",
    inclusions: ["Rediseño UI/UX", "Mobile-first", "Mejora velocidad"],
    exclusions: ["Nuevas secciones", "Nuevas funciones"],
    imgs: {
      thumbnails: ["/images/products/web-premium.png"],
      previews: ["/images/products/web-premium.png"],
    },
  },

  // --- Branding ---
  {
    id: 201,
    title: "Logo Starter Pack",
    category: "Branding",
    price: 120000,
    reviews: 5,
    description: "2–3 propuestas, 2 rondas ajustes, PNG/SVG + favicon.",
    inclusions: ["2-3 Propuestas de Logo", "PNG/SVG + Favicon", "2 Rondas de ajustes"],
    exclusions: ["Manual de marca extenso"],
    imgs: {
      thumbnails: ["/images/products/product-logo.png"],
      previews: ["/images/products/product-logo.png"],
    },
  },
  {
    id: 202,
    title: "Logo Pro + Manual Básico",
    category: "Branding",
    price: 250000,
    reviews: 5,
    description: "Variaciones + guía uso (colores, tamaños).",
    inclusions: ["Variaciones de logo", "Guía de uso colores/tipos", "Archivos editables"],
    exclusions: ["Aplicaciones específicas"],
    imgs: {
      thumbnails: ["/images/products/product-logo.png"],
      previews: ["/images/products/product-logo.png"],
    },
  },
  {
    id: 203,
    title: "Kit Identidad Visual",
    category: "Branding",
    price: 380000,
    reviews: 5,
    description: "Logo, paleta, tipografías, estilos foto/íconos, ejemplos uso.",
    inclusions: ["Logo completo", "Paleta & Tipografías", "Estilos visuales"],
    exclusions: ["Producción física (papelería)"],
    imgs: {
      thumbnails: ["/images/products/product-logo.png"],
      previews: ["/images/products/product-logo.png"],
    },
  },
  {
    id: 204,
    title: "Redes Sociales Mensual Lite",
    category: "Social",
    price: 160000,
    reviews: 4,
    description: "10 piezas/mes (posts + stories), 1 red.",
    inclusions: ["10 piezas gráficas", "Adaptación 1 red", "Entrega mensual"],
    exclusions: ["Estrategia", "Gestión de cuentas"],
    imgs: {
      thumbnails: ["/images/products/product-social.png"],
      previews: ["/images/products/product-social.png"],
    },
  },
  {
    id: 205,
    title: "Pack Plantillas Editables",
    category: "Branding",
    price: 140000,
    reviews: 4,
    description: "15 plantillas Canva/Figma (anuncios, posts, stories).",
    inclusions: ["15 Plantillas editables", "Formato Canva/Figma", "Guía de edición"],
    exclusions: ["Creación custom mensual"],
    imgs: {
      thumbnails: ["/images/products/branding-premium.png"],
      previews: ["/images/products/branding-premium.png"],
    },
  },

  // --- Ads ---
  {
    id: 301,
    title: "Setup Meta Ads",
    category: "Ads",
    price: 180000,
    reviews: 5,
    description: "BM, píxel, 1–2 campañas, 3–6 anuncios base.",
    inclusions: ["Configuración Business Manager", "Pixel Setup", "1-2 Campañas iniciales"],
    exclusions: ["Presupuesto de ads"],
    imgs: {
      thumbnails: ["/images/products/product-ads.png"],
      previews: ["/images/products/product-ads.png"],
    },
  },
  {
    id: 302,
    title: "Gestión Mensual Lite Meta Ads",
    category: "Ads",
    price: 220000,
    reviews: 4,
    description: "Ajustes semanales, 1 recambio creativos, reporte.",
    inclusions: ["Optimización semanal", "Reporte mensual", "1 Recambio creativos"],
    exclusions: ["Test A/B avanzado"],
    imgs: {
      thumbnails: ["/images/products/product-ads.png"],
      previews: ["/images/products/product-ads.png"],
    },
  },
  {
    id: 303,
    title: "Setup Google Ads Búsqueda",
    category: "Ads",
    price: 180000,
    reviews: 5,
    description: "1 campaña, 3–5 grupos, keywords base, extensiones.",
    inclusions: ["Investigación keywords", "1 Campaña Búsqueda", "Configuración conversiones"],
    exclusions: ["Presupuesto ads"],
    imgs: {
      thumbnails: ["/images/products/product-ads.png"],
      previews: ["/images/products/product-ads.png"],
    },
  },

  // --- Content & Automation ---
  {
    id: 401,
    title: "Pack Textos Web Básico",
    category: "Content",
    price: 180000,
    reviews: 4,
    description: "Home + Servicios + Sobre Nosotros (SEO).",
    inclusions: ["Textos persuasivos", "Enfoque SEO básico", "3 Páginas"],
    exclusions: ["Investigación keywords profunda"],
    imgs: {
      thumbnails: ["/images/products/web-premium.png"],
      previews: ["/images/products/web-premium.png"],
    },
  },
  {
    id: 402,
    title: "Secuencia Emails Bienvenida",
    category: "Content",
    price: 110000,
    reviews: 4,
    description: "3 emails (bienvenida, propuesta, oferta).",
    inclusions: ["3 Emails redactados", "Estrategia de secuencia", "Asuntos gancheros"],
    exclusions: ["Configuración plataforma"],
    imgs: {
      thumbnails: ["/images/products/web-premium.png"],
      previews: ["/images/products/web-premium.png"],
    },
  },
  {
    id: 403,
    title: "Guion Chatbot/WhatsApp FAQ",
    category: "Automation",
    price: 180000,
    reviews: 3,
    description: "Flujos FAQ, objeciones, cierre citas.",
    inclusions: ["Árbol de decisiones", "Respuestas a objeciones", "Scripts de cierre"],
    exclusions: ["Implementación técnica"],
    imgs: {
      thumbnails: ["/images/products/ads-premium.png"],
      previews: ["/images/products/ads-premium.png"],
    },
  },

  // --- Audits ---
  {
    id: 501,
    title: "Auditoría Web Rápida",
    category: "Audit",
    price: 90000,
    reviews: 5,
    description: "Velocidad, UX móvil, claridad mensajes.",
    inclusions: ["Análisis velocidad", "Checklist UX móvil", "Reporte mejoras"],
    exclusions: ["Implementación de cambios"],
    imgs: {
      thumbnails: ["/images/products/branding-premium.png"],
      previews: ["/images/products/branding-premium.png"],
    },
  },
  {
    id: 502,
    title: "Plan Contenidos 30 Días",
    category: "Content",
    price: 160000,
    reviews: 4,
    description: "Calendario posts, titulares, CTAs.",
    inclusions: ["Calendario editorial", "Ideas de contenido", "Copy para captions"],
    exclusions: ["Diseño gráfico"],
    imgs: {
      thumbnails: ["/images/products/product-social.png"],
      previews: ["/images/products/product-social.png"],
    },
  },

  // --- Packs Turnkey ---
  {
    id: 601,
    title: "Lanzamiento Negocio Local",
    category: "Pack",
    price: 520000,
    reviews: 5,
    description: "GBP optimizado + Landing + 5 posts + Meta Ads setup.",
    inclusions: ["Google Business Profile", "Landing Page", "5 Posts Redes", "Setup Ads"],
    exclusions: ["Presupuesto ads"],
    imgs: {
      thumbnails: ["/images/products/pack-premium.png"],
      previews: ["/images/products/pack-premium.png"],
    },
  },
  {
    id: 602,
    title: "Presencia Online Completa",
    category: "Pack",
    price: 880000,
    reviews: 5,
    description: "Web básica + logo starter + setup ads.",
    inclusions: ["Web Corporativa", "Logo Starter", "Setup Campañas"],
    exclusions: ["Gestión continua"],
    imgs: {
      thumbnails: ["/images/products/pack-premium.png"],
      previews: ["/images/products/pack-premium.png"],
    },
  },
  {
    id: 603,
    title: "E-commerce que Vende",
    category: "Pack",
    price: 1150000,
    reviews: 5,
    description: "E-commerce + textos + remarketing básico.",
    inclusions: ["Tienda Online", "Copywriting fichas", "Remarketing Setup"],
    exclusions: ["Carga masiva inventario"],
    imgs: {
      thumbnails: ["/images/products/product-ecommerce.png"],
      previews: ["/images/products/product-ecommerce.png"],
    },
  },
];

export default shopData;
